/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import io.findify.s3mock.S3Mock;

import java.net.URI;
import java.time.Duration;

import software.amazon.awssdk.auth.credentials.AnonymousCredentialsProvider;

import software.amazon.awssdk.http.SdkHttpClient;
import software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient;

import software.amazon.awssdk.regions.Region;

import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.S3Configuration;


public final class App {

    public static void main(String[] args) {

	var s3Api = new S3Mock.Builder()
			.withPort(8098)
			.withInMemoryBackend()
			.build();
	s3Api.start();

	var client = S3Client.builder()
			.httpClient(UrlConnectionHttpClient.create())
			.endpointOverride(URI.create("http://localhost:8098"))
			.credentialsProvider(AnonymousCredentialsProvider.create())
			.serviceConfiguration(S3Configuration.builder()
					.pathStyleAccessEnabled(true)
					.build())

			.region(Region.US_WEST_2)
			.build();

	
	/* Do stuff here */


	client.close();
	s3Api.shutdown();
    }
}
